// <auto-generated />
using DeliveryServiceApi.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliveryServiceApi.Migrations
{
    [DbContext(typeof(DeliveryContext))]
    [Migration("20190215110150_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("DeliveryServiceApi.Entities.DeliveryEntity", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseCost");

                    b.Property<double>("Distance");

                    b.Property<int>("Floor");

                    b.Property<bool>("GoldRated");

                    b.Property<bool>("HasCoupen");

                    b.Property<bool>("NewCustomer");

                    b.Property<double>("TotalCost");

                    b.Property<bool>("WeekendDelivery");

                    b.HasKey("id");

                    b.ToTable("DeliveryEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
